CREATE DATABASE gc;
GRANT ALL PRIVILEGES ON DATABASE gc TO gcuser;

\c gc;

CREATE TABLE vehicles (
  id serial primary key,
  vin varchar,
  plateissuer varchar,
  platevalue varchar,
  make varchar,
  model varchar,
  year int,
  trim varchar,
  package varchar,
  nickname varchar,
  colorname varchar,
  colorhex varchar
);

CREATE TABLE maintenanceactivities (
  id serial primary key,
  activity varchar
);

CREATE TABLE maintenancerecords (
  id serial primary key,
  vehicleid int,
  activityid int,
  dateperformed varchar,
  mileage int
);

CREATE TABLE maintenanceschedule (
  id serial primary key,
	vehicleid int,
	activityid int,
	intervalvalue int,
	intervalunit varchar
);

CREATE TABLE vindata (
  VIN varchar primary key,
  ABS varchar,
  ActiveSafetySysNote varchar,
  AdaptiveCruiseControl varchar,
  AdaptiveDrivingBeam varchar,
  AdaptiveHeadlights varchar,
  AdditionalErrorText varchar,
  AirBagLocCurtain varchar,
  AirBagLocFront varchar,
  AirBagLocKnee varchar,
  AirBagLocSeatCushion varchar,
  AirBagLocSide varchar,
  AutoReverseSystem varchar,
  AutomaticPedestrianAlertingSound varchar,
  AxleConfiguration varchar,
  Axles varchar,
  BasePrice varchar,
  BatteryA varchar,
  BatteryA_to varchar,
  BatteryCells varchar,
  BatteryInfo varchar,
  BatteryKWh varchar,
  BatteryKWh_to varchar,
  BatteryModules varchar,
  BatteryPacks varchar,
  BatteryType varchar,
  BatteryV varchar,
  BatteryV_to varchar,
  BedLengthIN varchar,
  BedType varchar,
  BlindSpotIntervention varchar,
  BlindSpotMon varchar,
  BodyCabType varchar,
  BodyClass varchar,
  BrakeSystemDesc varchar,
  BrakeSystemType varchar,
  BusFloorConfigType varchar,
  BusLength varchar,
  BusType varchar,
  CAN_AACN varchar,
  CIB varchar,
  CashForClunkers varchar,
  ChargerLevel varchar,
  ChargerPowerKW varchar,
  CoolingType varchar,
  CurbWeightLB varchar,
  CustomMotorcycleType varchar,
  DaytimeRunningLight varchar,
  DestinationMarket varchar,
  DisplacementCC varchar,
  DisplacementCI varchar,
  DisplacementL varchar,
  Doors varchar,
  DriveType varchar,
  DriverAssist varchar,
  DynamicBrakeSupport varchar,
  EDR varchar,
  ESC varchar,
  EVDriveUnit varchar,
  ElectrificationLevel varchar,
  EngineConfiguration varchar,
  EngineCycles varchar,
  EngineCylinders varchar,
  EngineHP varchar,
  EngineHP_to varchar,
  EngineKW varchar,
  EngineManufacturer varchar,
  EngineModel varchar,
  EntertainmentSystem varchar,
  ErrorCode varchar,
  ErrorText varchar,
  ForwardCollisionWarning varchar,
  FuelInjectionType varchar,
  FuelTypePrimary varchar,
  FuelTypeSecondary varchar,
  GCWR varchar,
  GCWR_to varchar,
  GVWR varchar,
  GVWR_to varchar,
  KeylessIgnition varchar,
  LaneCenteringAssistance varchar,
  LaneDepartureWarning varchar,
  LaneKeepSystem varchar,
  LowerBeamHeadlampLightSource varchar,
  Make varchar,
  MakeID varchar,
  Manufacturer varchar,
  ManufacturerId varchar,
  Model varchar,
  ModelID varchar,
  ModelYear varchar,
  MotorcycleChassisType varchar,
  MotorcycleSuspensionType varchar,
  NCSABodyType varchar,
  NCSAMake varchar,
  NCSAMapExcApprovedBy varchar,
  NCSAMapExcApprovedOn varchar,
  NCSAMappingException varchar,
  NCSAModel varchar,
  NCSANote varchar,
  NonLandUse varchar,
  Note varchar,
  OtherBusInfo varchar,
  OtherEngineInfo varchar,
  OtherMotorcycleInfo varchar,
  OtherRestraintSystemInfo varchar,
  OtherTrailerInfo varchar,
  ParkAssist varchar,
  PedestrianAutomaticEmergencyBraking varchar,
  PlantCity varchar,
  PlantCompanyName varchar,
  PlantCountry varchar,
  PlantState varchar,
  PossibleValues varchar,
  Pretensioner varchar,
  RearAutomaticEmergencyBraking varchar,
  RearCrossTrafficAlert varchar,
  RearVisibilitySystem varchar,
  SAEAutomationLevel varchar,
  SAEAutomationLevel_to varchar,
  SeatBeltsAll varchar,
  SeatRows varchar,
  Seats varchar,
  SemiautomaticHeadlampBeamSwitching varchar,
  Series varchar,
  Series2 varchar,
  SteeringLocation varchar,
  SuggestedVIN varchar,
  TPMS varchar,
  TopSpeedMPH varchar,
  TrackWidth varchar,
  TractionControl varchar,
  TrailerBodyType varchar,
  TrailerLength varchar,
  TrailerType varchar,
  TransmissionSpeeds varchar,
  TransmissionStyle varchar,
  Trim varchar,
  Trim2 varchar,
  Turbo varchar,
  ValveTrainDesign varchar,
  VehicleDescriptor varchar,
  VehicleType varchar,
  WheelBaseLong varchar,
  WheelBaseShort varchar,
  WheelBaseType varchar,
  WheelSizeFront varchar,
  WheelSizeRear varchar,
  Wheels varchar,
  Windows varchar
);

/* static data */
INSERT INTO maintenanceactivities (activity) VALUES
  ('Oil Change'),
  ('Tire Rotation'),
  ('Brakes: Change Pads'),
  ('Brakes: Change Rotors'),
  ('Brakes: Change Both Pads & Rotors'),
  ('Replace Battery');

/* insert test data */
INSERT INTO vehicles (vin, plateissuer, platevalue, make, model, year, trim, package, nickname, colorname, colorhex) VALUES
  ('1C4HJXDG3MW709024', 'VA', 'UDS-1963', 'Jeep', 'Wrangler Unlimited', 2020, 'Sport', 'Willys', 'Junebug', 'Hellayella', 'fdb93c'),
  ('5TDYK3DC9DS368862', 'VA', 'ALLEARS', 'Toyota', 'Sienna', 2013, 'Limited', '', '', 'Shoreline Blue Pearl', '4e5269');
INSERT INTO maintenancerecords (vehicleid, activityid, dateperformed, mileage) VALUES
  (1, 1, '1/6/2025', 27925);
